apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-poc-gitops-1
  labels:
    app: nginx-poc-gitops-1
    project: poc-gitops-1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-poc-gitops-1
  template:
    metadata:
      labels:
        app: nginx-poc-gitops-1
        project: poc-gitops-1
    spec:
      containers:
      - name: nginx
        image: nginx:1.25-alpine
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10