apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

commonLabels:
  app: nginx-poc-gitops-1
  project: poc-gitops-1

images:
- name: nginx
  newTag: 1.25-alpine